function [b, resrms] = broken_line_fit_and_plot(x, y, breaks, varargin)
  [TOP,LW,ZERO,W] = getKeywordParams(top = true ...
    ,                                linewidth = 4 ...
    ,                                zero = false ...
    ,                                weight = 0);
  [b, resrms] = broken_line_regress(x, y, breaks, zero=ZERO, weight=W);
  broken_line_plot(b, top=TOP, linewidth=LW)
end
